<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


<!-- ===================== Wheel xacro =========================================

  params:
  - prefix [string]: used to diferentiate the link and joint name;
  - reflect [1/-1]: value to set the side of the wheel;
  - wheel_props [dictionary]: wheel properties;
  - base_props [dictionary]: base link properties;
  - mesh [string]: file name of the wheel mesh;
    - DEFAULT Value -> Empty string
-->

<xacro:macro name="wheel"
               params="prefix reflect wheel_props base_props ">

  <xacro:property name="pos_x_joint"
     value="${(base_props['base']['x_size']/2) - wheel_props['x_offset']}"/>
  <xacro:property name="pos_y_joint"
    value="${(base_props['base']['y_size']/2) + wheel_props['y_offset'] + (wheel_props['length']/2)}"/>
  <xacro:property name="pos_z_joint" value="${wheel_props['z_offset']}"/>

    <link name="${prefix}_wheel">
    <xacro:if value="${wheel_props['mesh'] != '' }" >
      <visual>
        <origin xyz="0.0 0 0" rpy="${pi} 0 ${pi/2}"/>
        <geometry>
          <xacro:if value="${wheel_props['scale'] == '' }" >
            <mesh filename="package://rusty_description/meshes/${wheel_props['mesh']}" />
          </xacro:if>
          <xacro:unless value="${wheel_props['scale'] == '' }" >
            <mesh filename="package://rusty_description/meshes/${wheel_props['mesh']}" scale="${wheel_props['scale']}" />
          </xacro:unless>
        </geometry>
        <material name="dark_grey"/>
      </visual>
    </xacro:if>
    <xacro:if value="${wheel_props['mesh'] == '' }" >
      <visual>
        <origin xyz="0.0 0 0" rpy="${pi/2} 0 0"/>
         <geometry>
         <cylinder radius="${wheel_props['radius']}" length="${wheel_props['length']}"/>
        </geometry>
        <material name="red"/>
      </visual>
    </xacro:if>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_props['radius']}" length="${wheel_props['length']}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_props['mass']}"
                              r="${wheel_props['radius']}"
                              l="${wheel_props['length']}"
                              o_xyz="0.0 0.0 0.0"
                              o_rpy="${pi/2.0} 0.0 0.0" >
      </xacro:cylinder_inertia>
    </link>


    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${pos_x_joint} ${reflect* pos_y_joint} ${pos_z_joint}" rpy="0 0 0"/>
      <dynamics damping="0.01" friction="0.0"/>
    </joint>

  </xacro:macro>
  </robot>